version: '3.8'

services:
  app:
    image: ghcr.io/${GITHUB_REPOSITORY,,}:latest
    restart: always
    env_file:
      - .env
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    ports:
      - "80:80"
