name: Docker Build and Push

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions: write-all
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GHCR_REGISTRY: ghcr.io
  QINGCLOUD_REGISTRY: dockerhub.qingcloud.com
  IMAGE_NAME: ${{ github.repository }}-ui

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert repository owner to lowercase
        run: |
          echo "OWNER_LOWER=${GITHUB_REPOSITORY_OWNER,,}" >>${GITHUB_ENV}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to QingCloud Registry
        run: |
          docker login -u ${{ secrets.QINGCLOUD_DOCKER_USERNAME }} -p ${{ secrets.QINGCLOUD_DOCKER_PASSWORD }} ${{ env.QINGCLOUD_REGISTRY }}

      - name: Build and push to GitHub Registry
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.GHCR_REGISTRY }}/${{ env.OWNER_LOWER }}/bilibili-live-tools-ui:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push to QingCloud Registry
        run: |
          docker build -t ${{ env.QINGCLOUD_REGISTRY }}/${{ secrets.QINGCLOUD_NAMESPACE }}/bilibili-live-tools-ui:latest .
          docker push ${{ env.QINGCLOUD_REGISTRY }}/${{ secrets.QINGCLOUD_NAMESPACE }}/bilibili-live-tools-ui:latest
